name: Tweet Schedule

on:
  schedule:
    - cron: '*/3 * * * *' # The workflow runs every 3 min.

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests requests_oauthlib

      - name: Run Python Script
        run: python generate_quote_tweet.py
        env:
          CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
